# Generated by Django 4.2.9 on 2024-01-09 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('over', models.BooleanField(default=False)),
                ('chat_id', models.CharField(max_length=2555)),
                ('message_id', models.CharField(max_length=2555, null=True)),
                ('state', models.CharField(default='collecting', max_length=255)),
                ('waiting_time', models.DateTimeField(default=datetime.datetime(2024, 1, 9, 14, 49, 26, 473445, tzinfo=datetime.timezone.utc))),
                ('waiting_time2', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_super_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_choice', models.PositiveIntegerField(blank=True, null=True)),
                ('user2_choice', models.PositiveIntegerField(blank=True, null=True)),
                ('chat_id', models.CharField(max_length=2555)),
                ('message_id', models.CharField(max_length=2555, null=True)),
                ('waiting_time2', models.IntegerField(default=10)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penalty_app.game')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='penalty_app.telegramuser')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='penalty_app.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_game', to='penalty_app.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_player', to='penalty_app.telegramuser')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='penalty_app.telegramuser'),
        ),
    ]
