# Generated by Django 4.2.9 on 2024-01-09 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 16, 52, 7, 868231, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='waiting_time2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='round',
            name='waiting_time2',
            field=models.IntegerField(default=12),
        ),
    ]
