# Generated by Django 4.2.9 on 2024-01-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('started', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to='penalty_app.telegramuser')),
            ],
        ),
    ]
