# Generated by Django 4.2.9 on 2024-01-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chat_id',
            field=models.CharField(default=1, max_length=2555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='message_id',
            field=models.CharField(max_length=2555, null=True),
        ),
    ]
