# Generated by Django 4.2.9 on 2024-01-09 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0002_round_moved_alter_game_waiting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 17, 22, 5, 421897, tzinfo=datetime.timezone.utc)),
        ),
    ]
