# Generated by Django 4.2.9 on 2024-01-09 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0003_alter_game_waiting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='waiting_time',
        ),
        migrations.AddField(
            model_name='game',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 22, 37, 59, 482839, tzinfo=datetime.timezone.utc)),
        ),
    ]
