# Generated by Django 4.2.9 on 2024-01-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0003_game_chat_id_game_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='started',
            new_name='over',
        ),
    ]
