# Generated by Django 4.2.9 on 2024-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0004_rename_started_game_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(default='collecting', max_length=255),
        ),
    ]
