# Generated by Django 4.2.9 on 2024-01-09 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0004_remove_game_waiting_time_game_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 22, 53, 4, 673663, tzinfo=datetime.timezone.utc)),
        ),
    ]
