# Generated by Django 4.2.9 on 2024-01-07 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0007_alter_game_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 13, 36, 55, 946918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_choice', models.CharField(max_length=1)),
                ('user2_choice', models.CharField(max_length=1)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penalty_app.game')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='penalty_app.telegramuser')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='penalty_app.telegramuser')),
            ],
        ),
    ]
