# Generated by Django 4.2.9 on 2024-01-07 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0008_alter_game_waiting_time_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='chat_id',
            field=models.CharField(default=1, max_length=2555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='message_id',
            field=models.CharField(max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 13, 38, 36, 36369, tzinfo=datetime.timezone.utc)),
        ),
    ]
