# Generated by Django 4.2.9 on 2024-01-07 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0009_round_chat_id_round_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 13, 54, 6, 63838, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='round',
            name='user1_choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='user2_choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
