# Generated by Django 4.2.9 on 2024-01-07 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0012_alter_game_waiting_time_alter_round_user1_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 17, 37, 10, 337776, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 17, 37, 10, 337776, tzinfo=datetime.timezone.utc)),
        ),
    ]
