# Generated by Django 4.2.9 on 2024-01-08 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penalty_app', '0013_round_waiting_time_alter_game_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 3, 14, 1, 145974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='round',
            name='waiting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 3, 14, 1, 145974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight', to='penalty_app.telegramuser')),
                ('five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five', to='penalty_app.telegramuser')),
                ('four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four', to='penalty_app.telegramuser')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_game', to='penalty_app.game')),
                ('nine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nine', to='penalty_app.telegramuser')),
                ('one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one', to='penalty_app.telegramuser')),
                ('seven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven', to='penalty_app.telegramuser')),
                ('six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six', to='penalty_app.telegramuser')),
                ('ten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten', to='penalty_app.telegramuser')),
                ('three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three', to='penalty_app.telegramuser')),
                ('two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two', to='penalty_app.telegramuser')),
            ],
        ),
    ]
